import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'it' | 'de' | 'pl' | 'pt' | 'fr' | 'zh' | 'ru' | 'nl' | 'tr' | 'ja' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Landing Page
    'landing.title': 'Manager Game | Join the free football world',
    'landing.getTeam': 'Get your team',
    'landing.getTeamDesc': 'Get started with your own team - we are always looking for new talent!',
    'landing.signIn': 'Sign In',
    'landing.signUp': 'Sign up',
    'landing.buildTrain': 'Build and train your team',
    'landing.buildTrainDesc': 'Develop your team through training. Find your finances. Pick your best players.',
    'landing.compete': 'Compete in leagues',
    'landing.competeDesc': 'Join competitive leagues and tournaments. Rise through divisions.',
    'landing.matchExp': 'Match experience',
    'landing.matchExpDesc': 'Watch live matches with our real-time match simulator.',
    'landing.community': 'Community',
    'landing.communityDesc': 'Join a vibrant community of managers from around the world.',
    'landing.discordTitle': 'Join the development community sharing ideas and insights!',
    'landing.chooseLanguage': 'Choose language',

    // Navigation
    'nav.myClub': 'My Club',
    'nav.world': 'World',
    'nav.groups': 'Groups',
    'nav.forums': 'Forums',
    'nav.community': 'Community',
    'nav.help': 'Help',
    'nav.premium': 'Premium',
    'nav.mailbox': 'Mailbox',

    // Sidebar Menu
    'sidebar.overview': 'Overview',
    'sidebar.club': 'Club',
    'sidebar.players': 'Players',
    'sidebar.training': 'Training',
    'sidebar.matches': 'Matches',
    'sidebar.league': 'League',
    'sidebar.stadium': 'Stadium',
    'sidebar.finances': 'Finances',
    'sidebar.transfers': 'Transfers',
    'sidebar.challenges': 'Challenges',
    'sidebar.manager': 'Manager',

    // Auth
    'auth.signInTitle': 'Sign in to',
    'auth.signInDesc': 'Enter your email to access your team',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.signIn': 'Sign In',
    'auth.signingIn': 'Signing in...',
    'auth.noAccount': "Don't have an account?",
    'auth.createAccount': 'Create an Account',
    'auth.createAccountDesc': 'Sign up to start your soccer manager career',
    'auth.haveAccount': 'Already have an account?',
    'auth.terms': 'By continuing, you agree to our Terms of Service and Privacy Policy.',

    // Player attributes
    'player.skill.finishing': 'Finishing', 'player.skill.pace': 'Pace',
    'player.skill.passing': 'Passing', 'player.skill.defense': 'Defense',
    'player.skill.dribbling': 'Dribbling', 'player.skill.heading': 'Heading',
    'player.skill.stamina': 'Stamina', 'player.skill.goalkeeper': 'Goalkeeper',
    'player.category.technical': 'Technical', 'player.category.physical': 'Physical',
    'player.form.excellent': 'Excellent', 'player.form.good': 'Good',
    'player.form.average': 'Average', 'player.form.poor': 'Poor',
    'player.fitness': 'Fitness', 'player.goals': 'Goals', 'player.assists': 'Assists',
    'player.value': 'Value', 'player.wage': 'Wage', 'player.age': 'Age',
  },
  es: {
    // Landing Page
    'landing.title': 'Juego de Manager | Únete al mundo del fútbol gratuito',
    'landing.getTeam': 'Consigue tu equipo',
    'landing.getTeamDesc': '¡Comienza con tu propio equipo - siempre estamos buscando nuevos talentos!',
    'landing.signIn': 'Iniciar Sesión',
    'landing.signUp': 'Registrarse',
    'landing.buildTrain': 'Construye y entrena tu equipo',
    'landing.buildTrainDesc': 'Desarrolla tu equipo mediante entrenamiento. Gestiona tus finanzas. Elige tus mejores jugadores.',
    'landing.compete': 'Compite en ligas',
    'landing.competeDesc': 'Únete a ligas competitivas y torneos. Asciende de división.',
    'landing.matchExp': 'Experiencia de partido',
    'landing.matchExpDesc': 'Observa partidos en vivo con nuestro simulador en tiempo real.',
    'landing.community': 'Comunidad',
    'landing.communityDesc': 'Únete a una comunidad vibrante de managers de todo el mundo.',
    'landing.discordTitle': '¡Únete a la comunidad de desarrollo compartiendo ideas y conocimientos!',
    'landing.chooseLanguage': 'Elegir idioma',

    // Navigation
    'nav.myClub': 'Mi Club',
    'nav.world': 'Mundo',
    'nav.groups': 'Grupos',
    'nav.forums': 'Foros',
    'nav.community': 'Comunidad',
    'nav.help': 'Ayuda',
    'nav.premium': 'Premium',
    'nav.mailbox': 'Buzón',

    // Sidebar Menu
    'sidebar.overview': 'Resumen',
    'sidebar.club': 'Club',
    'sidebar.players': 'Jugadores',
    'sidebar.training': 'Entrenamiento',
    'sidebar.matches': 'Partidos',
    'sidebar.league': 'Liga',
    'sidebar.stadium': 'Estadio',
    'sidebar.finances': 'Finanzas',
    'sidebar.transfers': 'Transferencias',
    'sidebar.challenges': 'Desafíos',
    'sidebar.manager': 'Manager',

    // Auth
    'auth.signInTitle': 'Iniciar sesión en',
    'auth.signInDesc': 'Introduce tu email para acceder a tu equipo',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.signIn': 'Iniciar Sesión',
    'auth.signingIn': 'Iniciando sesión...',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.createAccount': 'Crear una Cuenta',
    'auth.createAccountDesc': 'Regístrate para comenzar tu carrera como manager de fútbol',
    'auth.haveAccount': '¿Ya tienes una cuenta?',
    'auth.terms': 'Al continuar, aceptas nuestros Términos de Servicio y Política de Privacidad.',

    // Atributos de jugador
    'player.skill.finishing': 'Definición', 'player.skill.pace': 'Velocidad',
    'player.skill.passing': 'Pase', 'player.skill.defense': 'Defensa',
    'player.skill.dribbling': 'Regate', 'player.skill.heading': 'Cabeceo',
    'player.skill.stamina': 'Resistencia', 'player.skill.goalkeeper': 'Portería',
    'player.category.technical': 'Técnicas', 'player.category.physical': 'Físicas',
    'player.form.excellent': 'Excelente', 'player.form.good': 'Buena',
    'player.form.average': 'Normal', 'player.form.poor': 'Mala',
    'player.fitness': 'Forma Física', 'player.goals': 'Goles', 'player.assists': 'Asistencias',
    'player.value': 'Valor', 'player.wage': 'Salario', 'player.age': 'Edad',
  },
  it: {
    // Landing Page
    'landing.title': 'Gioco Manager | Unisciti al mondo del calcio gratuito',
    'landing.getTeam': 'Ottieni la tua squadra',
    'landing.getTeamDesc': 'Inizia con la tua squadra - stiamo sempre cercando nuovi talenti!',
    'landing.signIn': 'Accedi',
    'landing.signUp': 'Registrati',
    'landing.buildTrain': 'Costruisci e allena la tua squadra',
    'landing.buildTrainDesc': 'Sviluppa la tua squadra attraverso allenamenti. Gestisci le finanze. Scegli i tuoi migliori giocatori.',
    'landing.compete': 'Competi nelle leghe',
    'landing.competeDesc': 'Unisciti a leghe competitive e tornei. Sali di divisione.',
    'landing.matchExp': 'Esperienza di partita',
    'landing.matchExpDesc': 'Guarda partite dal vivo con il nostro simulatore in tempo reale.',
    'landing.community': 'Comunità',
    'landing.communityDesc': 'Unisciti a una comunità vibrante di manager da tutto il mondo.',
    'landing.discordTitle': 'Unisciti alla comunità di sviluppo condividendo idee e intuizioni!',
    'landing.chooseLanguage': 'Scegli lingua',

    // Navigation
    'nav.myClub': 'Il Mio Club',
    'nav.world': 'Mondo',
    'nav.groups': 'Gruppi',
    'nav.forums': 'Forum',
    'nav.community': 'Comunità',
    'nav.help': 'Aiuto',
    'nav.premium': 'Premium',
    'nav.mailbox': 'Posta',

    // Sidebar Menu
    'sidebar.overview': 'Panoramica',
    'sidebar.club': 'Club',
    'sidebar.players': 'Giocatori',
    'sidebar.training': 'Allenamento',
    'sidebar.matches': 'Partite',
    'sidebar.league': 'Lega',
    'sidebar.stadium': 'Stadio',
    'sidebar.finances': 'Finanze',
    'sidebar.transfers': 'Trasferimenti',
    'sidebar.challenges': 'Sfide',
    'sidebar.manager': 'Manager',

    // Auth
    'auth.signInTitle': 'Accedi a',
    'auth.signInDesc': 'Inserisci la tua email per accedere alla tua squadra',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Password dimenticata?',
    'auth.signIn': 'Accedi',
    'auth.signingIn': 'Accedendo...',
    'auth.noAccount': 'Non hai un account?',
    'auth.createAccount': 'Crea un Account',
    'auth.createAccountDesc': 'Registrati per iniziare la tua carriera da manager di calcio',
    'auth.haveAccount': 'Hai già un account?',
    'auth.terms': 'Continuando, accetti i nostri Termini di Servizio e la Politica sulla Privacy.',

    // Attributi giocatore
    'player.skill.finishing': 'Finalizzazione', 'player.skill.pace': 'Velocità',
    'player.skill.passing': 'Passaggio', 'player.skill.defense': 'Difesa',
    'player.skill.dribbling': 'Dribbling', 'player.skill.heading': 'Colpo di testa',
    'player.skill.stamina': 'Resistenza', 'player.skill.goalkeeper': 'Portiere',
    'player.category.technical': 'Tecniche', 'player.category.physical': 'Fisiche',
    'player.form.excellent': 'Eccellente', 'player.form.good': 'Buona',
    'player.form.average': 'Nella media', 'player.form.poor': 'Scarsa',
    'player.fitness': 'Forma', 'player.goals': 'Gol', 'player.assists': 'Assist',
    'player.value': 'Valore', 'player.wage': 'Stipendio', 'player.age': 'Età',
  },
  de: {
    // Landing Page
    'landing.title': 'Manager-Spiel | Tritt der kostenlosen Fußballwelt bei',
    'landing.getTeam': 'Hol dir dein Team',
    'landing.getTeamDesc': 'Starte mit deinem eigenen Team - wir suchen immer nach neuen Talenten!',
    'landing.signIn': 'Anmelden',
    'landing.signUp': 'Registrieren',
    'landing.buildTrain': 'Baue und trainiere dein Team',
    'landing.buildTrainDesc': 'Entwickle dein Team durch Training. Verwalte deine Finanzen. Wähle deine besten Spieler.',
    'landing.compete': 'In Ligen antreten',
    'landing.competeDesc': 'Tritt kompetitiven Ligen und Turnieren bei. Steige in Divisionen auf.',
    'landing.matchExp': 'Spielerlebnis',
    'landing.matchExpDesc': 'Schaue Live-Spiele mit unserem Echtzeit-Simulator.',
    'landing.community': 'Gemeinschaft',
    'landing.communityDesc': 'Tritt einer lebendigen Gemeinschaft von Managern aus aller Welt bei.',
    'landing.discordTitle': 'Tritt der Entwicklungsgemeinschaft bei und teile Ideen und Einsichten!',
    'landing.chooseLanguage': 'Sprache wählen',

    // Navigation
    'nav.myClub': 'Mein Verein',
    'nav.world': 'Welt',
    'nav.groups': 'Gruppen',
    'nav.forums': 'Foren',
    'nav.community': 'Gemeinschaft',
    'nav.help': 'Hilfe',
    'nav.premium': 'Premium',
    'nav.mailbox': 'Postfach',

    // Sidebar Menu
    'sidebar.overview': 'Übersicht',
    'sidebar.club': 'Verein',
    'sidebar.players': 'Spieler',
    'sidebar.training': 'Training',
    'sidebar.matches': 'Spiele',
    'sidebar.league': 'Liga',
    'sidebar.stadium': 'Stadion',
    'sidebar.finances': 'Finanzen',
    'sidebar.transfers': 'Transfers',
    'sidebar.challenges': 'Herausforderungen',
    'sidebar.manager': 'Manager',

    // Auth
    'auth.signInTitle': 'Anmelden bei',
    'auth.signInDesc': 'Gib deine E-Mail ein, um auf dein Team zuzugreifen',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.signIn': 'Anmelden',
    'auth.signingIn': 'Anmeldung...',
    'auth.noAccount': 'Hast du kein Konto?',
    'auth.createAccount': 'Konto erstellen',
    'auth.createAccountDesc': 'Registriere dich, um deine Fußball-Manager-Karriere zu starten',
    'auth.haveAccount': 'Hast du bereits ein Konto?',
    'auth.terms': 'Durch Fortfahren stimmst du unseren Nutzungsbedingungen und der Datenschutzrichtlinie zu.',

    // Spieler-Attribute
    'player.skill.finishing': 'Abschluss', 'player.skill.pace': 'Tempo',
    'player.skill.passing': 'Pass', 'player.skill.defense': 'Abwehr',
    'player.skill.dribbling': 'Dribbling', 'player.skill.heading': 'Kopfball',
    'player.skill.stamina': 'Ausdauer', 'player.skill.goalkeeper': 'Torwart',
    'player.category.technical': 'Technisch', 'player.category.physical': 'Physisch',
    'player.form.excellent': 'Ausgezeichnet', 'player.form.good': 'Gut',
    'player.form.average': 'Durchschnittlich', 'player.form.poor': 'Schlecht',
    'player.fitness': 'Fitness', 'player.goals': 'Tore', 'player.assists': 'Vorlagen',
    'player.value': 'Marktwert', 'player.wage': 'Gehalt', 'player.age': 'Alter',
  },
  pl: {
    // Landing Page
    'landing.title': 'Gra Menedżerska | Dołącz do darmowego świata piłki nożnej',
    'landing.getTeam': 'Zdobądź swoją drużynę',
    'landing.getTeamDesc': 'Rozpocznij ze swoją drużyną - zawsze szukamy nowych talentów!',
    'landing.signIn': 'Zaloguj się',
    'landing.signUp': 'Zarejestruj się',
    'landing.buildTrain': 'Buduj i trenuj swoją drużynę',
    'landing.buildTrainDesc': 'Rozwijaj swoją drużynę poprzez treningi. Zarządzaj finansami. Wybierz najlepszych graczy.',
    'landing.compete': 'Rywalizuj w ligach',
    'landing.competeDesc': 'Dołącz do konkurencyjnych lig i turniejów. Awansuj w dywizjach.',
    'landing.matchExp': 'Doświadczenie meczowe',
    'landing.matchExpDesc': 'Oglądaj mecze na żywo z naszym symulatorem czasu rzeczywistego.',
    'landing.community': 'Społeczność',
    'landing.communityDesc': 'Dołącz do żywej społeczności menedżerów z całego świata.',
    'landing.discordTitle': 'Dołącz do społeczności deweloperskiej dzieląc się pomysłami i spostrzeżeniami!',
    'landing.chooseLanguage': 'Wybierz język',

    // Navigation
    'nav.myClub': 'Mój Klub',
    'nav.world': 'Świat',
    'nav.groups': 'Grupy',
    'nav.forums': 'Fora',
    'nav.community': 'Społeczność',
    'nav.help': 'Pomoc',
    'nav.premium': 'Premium',
    'nav.mailbox': 'Skrzynka',

    // Sidebar Menu
    'sidebar.overview': 'Przegląd',
    'sidebar.club': 'Klub',
    'sidebar.players': 'Zawodnicy',
    'sidebar.training': 'Trening',
    'sidebar.matches': 'Mecze',
    'sidebar.league': 'Liga',
    'sidebar.stadium': 'Stadion',
    'sidebar.finances': 'Finanse',
    'sidebar.transfers': 'Transfery',
    'sidebar.challenges': 'Wyzwania',
    'sidebar.manager': 'Menedżer',

    // Auth
    'auth.signInTitle': 'Zaloguj się do',
    'auth.signInDesc': 'Wprowadź swój email, aby uzyskać dostęp do swojej drużyny',
    'auth.email': 'Email',
    'auth.password': 'Hasło',
    'auth.forgotPassword': 'Zapomniałeś hasła?',
    'auth.signIn': 'Zaloguj się',
    'auth.signingIn': 'Logowanie...',
    'auth.noAccount': 'Nie masz konta?',
    'auth.createAccount': 'Utwórz Konto',
    'auth.createAccountDesc': 'Zarejestruj się, aby rozpocząć karierę menedżera piłkarskiego',
    'auth.haveAccount': 'Masz już konto?',
    'auth.terms': 'Kontynuując, zgadzasz się na nasze Warunki Usługi i Politykę Prywatności.',

    // Atrybuty zawodnika
    'player.skill.finishing': 'Wykończenie', 'player.skill.pace': 'Szybkość',
    'player.skill.passing': 'Podanie', 'player.skill.defense': 'Obrona',
    'player.skill.dribbling': 'Drybling', 'player.skill.heading': 'Główka',
    'player.skill.stamina': 'Wytrzymałość', 'player.skill.goalkeeper': 'Bramkarz',
    'player.category.technical': 'Techniczne', 'player.category.physical': 'Fizyczne',
    'player.form.excellent': 'Doskonała', 'player.form.good': 'Dobra',
    'player.form.average': 'Przeciętna', 'player.form.poor': 'Słaba',
    'player.fitness': 'Kondycja', 'player.goals': 'Gole', 'player.assists': 'Asysty',
    'player.value': 'Wartość', 'player.wage': 'Pensja', 'player.age': 'Wiek',
  },
  pt: {
    // Landing Page
    'landing.title': 'Jogo de Manager | Junte-se ao mundo do futebol gratuito',
    'landing.getTeam': 'Obtenha sua equipe',
    'landing.getTeamDesc': 'Comece com sua própria equipe - estamos sempre procurando novos talentos!',
    'landing.signIn': 'Entrar',
    'landing.signUp': 'Cadastrar-se',
    'landing.buildTrain': 'Construa e treine sua equipe',
    'landing.buildTrainDesc': 'Desenvolva sua equipe através de treinos. Gerencie suas finanças. Escolha seus melhores jogadores.',
    'landing.compete': 'Compita em ligas',
    'landing.competeDesc': 'Junte-se a ligas competitivas e torneios. Suba de divisão.',
    'landing.matchExp': 'Experiência de partida',
    'landing.matchExpDesc': 'Assista partidas ao vivo com nosso simulador em tempo real.',
    'landing.community': 'Comunidade',
    'landing.communityDesc': 'Junte-se a uma comunidade vibrante de managers de todo o mundo.',
    'landing.discordTitle': 'Junte-se à comunidade de desenvolvimento compartilhando ideias e insights!',
    'landing.chooseLanguage': 'Escolher idioma',

    // Navigation
    'nav.myClub': 'Meu Clube',
    'nav.world': 'Mundo',
    'nav.groups': 'Grupos',
    'nav.forums': 'Fóruns',
    'nav.community': 'Comunidade',
    'nav.help': 'Ajuda',
    'nav.premium': 'Premium',
    'nav.mailbox': 'Caixa de Mensagens',

    // Sidebar Menu
    'sidebar.overview': 'Visão Geral',
    'sidebar.club': 'Clube',
    'sidebar.players': 'Jogadores',
    'sidebar.training': 'Treinamento',
    'sidebar.matches': 'Partidas',
    'sidebar.league': 'Liga',
    'sidebar.stadium': 'Estádio',
    'sidebar.finances': 'Finanças',
    'sidebar.transfers': 'Transferências',
    'sidebar.challenges': 'Desafios',
    'sidebar.manager': 'Manager',

    // Auth
    'auth.signInTitle': 'Entrar em',
    'auth.signInDesc': 'Digite seu email para acessar sua equipe',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.forgotPassword': 'Esqueceu a senha?',
    'auth.signIn': 'Entrar',
    'auth.signingIn': 'Entrando...',
    'auth.noAccount': 'Não tem uma conta?',
    'auth.createAccount': 'Criar uma Conta',
    'auth.createAccountDesc': 'Cadastre-se para começar sua carreira como manager de futebol',
    'auth.haveAccount': 'Já tem uma conta?',
    'auth.terms': 'Ao continuar, você concorda com nossos Termos de Serviço e Política de Privacidade.',

    // Atributos do jogador
    'player.skill.finishing': 'Finalização', 'player.skill.pace': 'Velocidade',
    'player.skill.passing': 'Passe', 'player.skill.defense': 'Defesa',
    'player.skill.dribbling': 'Drible', 'player.skill.heading': 'Cabeceio',
    'player.skill.stamina': 'Resistência', 'player.skill.goalkeeper': 'Guarda-redes',
    'player.category.technical': 'Técnicas', 'player.category.physical': 'Físicas',
    'player.form.excellent': 'Excelente', 'player.form.good': 'Boa',
    'player.form.average': 'Normal', 'player.form.poor': 'Má',
    'player.fitness': 'Forma', 'player.goals': 'Golos', 'player.assists': 'Assistências',
    'player.value': 'Valor', 'player.wage': 'Salário', 'player.age': 'Idade',
  },
  fr: {
    // Landing Page
    'landing.title': 'Jeu de Manager | Rejoignez le monde du football gratuit',
    'landing.getTeam': 'Obtenez votre équipe',
    'landing.getTeamDesc': 'Commencez avec votre propre équipe - nous recherchons toujours de nouveaux talents !',
    'landing.signIn': 'Se connecter',
    'landing.signUp': 'S\'inscrire',
    'landing.buildTrain': 'Construisez et entraînez votre équipe',
    'landing.buildTrainDesc': 'Développez votre équipe grâce à l\'entraînement. Gérez vos finances. Choisissez vos meilleurs joueurs.',
    'landing.compete': 'Participez aux ligues',
    'landing.competeDesc': 'Rejoignez des ligues compétitives et des tournois. Montez en division.',
    'landing.matchExp': 'Expérience de match',
    'landing.matchExpDesc': 'Regardez des matchs en direct avec notre simulateur en temps réel.',
    'landing.community': 'Communauté',
    'landing.communityDesc': 'Rejoignez une communauté dynamique de managers du monde entier.',
    'landing.discordTitle': 'Rejoignez la communauté de développement en partageant des idées et des insights !',
    'landing.chooseLanguage': 'Choisir la langue',

    // Navigation
    'nav.myClub': 'Mon Club',
    'nav.world': 'Monde',
    'nav.groups': 'Groupes',
    'nav.forums': 'Forums',
    'nav.community': 'Communauté',
    'nav.help': 'Aide',
    'nav.premium': 'Premium',
    'nav.mailbox': 'Boîte mail',

    // Sidebar Menu
    'sidebar.overview': 'Aperçu',
    'sidebar.club': 'Club',
    'sidebar.players': 'Joueurs',
    'sidebar.training': 'Entraînement',
    'sidebar.matches': 'Matchs',
    'sidebar.league': 'Ligue',
    'sidebar.stadium': 'Stade',
    'sidebar.finances': 'Finances',
    'sidebar.transfers': 'Transferts',
    'sidebar.challenges': 'Défis',
    'sidebar.manager': 'Manager',

    // Auth
    'auth.signInTitle': 'Se connecter à',
    'auth.signInDesc': 'Entrez votre email pour accéder à votre équipe',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.signIn': 'Se connecter',
    'auth.signingIn': 'Connexion...',
    'auth.noAccount': 'Vous n\'avez pas de compte ?',
    'auth.createAccount': 'Créer un compte',
    'auth.createAccountDesc': 'Inscrivez-vous pour commencer votre carrière de manager de football',
    'auth.haveAccount': 'Vous avez déjà un compte ?',
    'auth.terms': 'En continuant, vous acceptez nos Conditions d\'utilisation et notre Politique de confidentialité.',

    // Attributs du joueur
    'player.skill.finishing': 'Finition', 'player.skill.pace': 'Vitesse',
    'player.skill.passing': 'Passe', 'player.skill.defense': 'Défense',
    'player.skill.dribbling': 'Dribble', 'player.skill.heading': 'Jeu de tête',
    'player.skill.stamina': 'Endurance', 'player.skill.goalkeeper': 'Gardien',
    'player.category.technical': 'Techniques', 'player.category.physical': 'Physiques',
    'player.form.excellent': 'Excellente', 'player.form.good': 'Bonne',
    'player.form.average': 'Moyenne', 'player.form.poor': 'Mauvaise',
    'player.fitness': 'Forme', 'player.goals': 'Buts', 'player.assists': 'Passes déc.',
    'player.value': 'Valeur', 'player.wage': 'Salaire', 'player.age': 'Âge',
  },
  zh: {
    // Landing Page
    'landing.title': '经理游戏 | 加入免费足球世界',
    'landing.getTeam': '获得您的球队',
    'landing.getTeamDesc': '从您自己的团队开始 - 我们一直在寻找新人才！',
    'landing.signIn': '登录',
    'landing.signUp': '注册',
    'landing.buildTrain': '建设和训练您的球队',
    'landing.buildTrainDesc': '通过训练发展您的团队。管理您的财务。选择您最好的球员。',
    'landing.compete': '参加联赛竞争',
    'landing.competeDesc': '加入竞争联赛和锦标赛。在分区中升级。',
    'landing.matchExp': '比赛体验',
    'landing.matchExpDesc': '通过我们的实时比赛模拟器观看现场比赛。',
    'landing.community': '社区',
    'landing.communityDesc': '加入来自世界各地经理的充满活力的社区。',
    'landing.discordTitle': '加入开发社区，分享想法和见解！',
    'landing.chooseLanguage': '选择语言',

    // Navigation
    'nav.myClub': '我的俱乐部',
    'nav.world': '世界',
    'nav.groups': '群组',
    'nav.forums': '论坛',
    'nav.community': '社区',
    'nav.help': '帮助',
    'nav.premium': '高级版',
    'nav.mailbox': '邮箱',

    // Sidebar Menu
    'sidebar.overview': '概览',
    'sidebar.club': '俱乐部',
    'sidebar.players': '球员',
    'sidebar.training': '训练',
    'sidebar.matches': '比赛',
    'sidebar.league': '联赛',
    'sidebar.stadium': '体育场',
    'sidebar.finances': '财务',
    'sidebar.transfers': '转会',
    'sidebar.challenges': '挑战',
    'sidebar.manager': '经理',

    // Auth
    'auth.signInTitle': '登录到',
    'auth.signInDesc': '输入您的电子邮件以访问您的团队',
    'auth.email': '电子邮件',
    'auth.password': '密码',
    'auth.forgotPassword': '忘记密码？',
    'auth.signIn': '登录',
    'auth.signingIn': '登录中...',
    'auth.noAccount': '没有账户？',
    'auth.createAccount': '创建账户',
    'auth.createAccountDesc': '注册开始您的足球经理职业生涯',
    'auth.haveAccount': '已有账户？',
    'auth.terms': '继续即表示您同意我们的服务条款和隐私政策。',

    // 球员属性
    'player.skill.finishing': '完成射门', 'player.skill.pace': '速度',
    'player.skill.passing': '传球', 'player.skill.defense': '防守',
    'player.skill.dribbling': '盘带', 'player.skill.heading': '头球',
    'player.skill.stamina': '体力', 'player.skill.goalkeeper': '守门',
    'player.category.technical': '技术', 'player.category.physical': '体能',
    'player.form.excellent': '出色', 'player.form.good': '良好',
    'player.form.average': '一般', 'player.form.poor': '差',
    'player.fitness': '体能状态', 'player.goals': '进球', 'player.assists': '助攻',
    'player.value': '市值', 'player.wage': '薪资', 'player.age': '年龄',
  },
  ru: {
    'landing.title': 'Игра Менеджера | Присоединяйся к миру бесплатного футбола',
    'landing.getTeam': 'Получи команду',
    'landing.getTeamDesc': 'Начни с собственной командой — мы всегда ищем новых менеджеров!',
    'landing.signIn': 'Войти',
    'landing.signUp': 'Регистрация',
    'landing.buildTrain': 'Стройте и тренируйте команду',
    'landing.buildTrainDesc': 'Развивайте команду через тренировки. Изучайте финансы. Выбирайте лучших игроков.',
    'landing.compete': 'Участвуйте в лигах',
    'landing.competeDesc': 'Вступайте в лиги и турниры. Поднимайтесь по дивизионам.',
    'landing.matchExp': 'Матчи',
    'landing.matchExpDesc': 'Наблюдайте за матчами в реальном времени с нашим симулятором.',
    'landing.community': 'Сообщество',
    'landing.communityDesc': 'Присоединяйтесь к сообществу менеджеров со всего мира.',
    'landing.discordTitle': 'Присоединяйтесь к сообществу разработчиков!',
    'landing.chooseLanguage': 'Выберите язык',
    'nav.myClub': 'Мой Клуб',
    'nav.world': 'Мир',
    'nav.groups': 'Группы',
    'nav.forums': 'Форумы',
    'nav.community': 'Сообщество',
    'nav.help': 'Помощь',
    'nav.premium': 'Премиум',
    'nav.mailbox': 'Почта',
    'sidebar.overview': 'Обзор',
    'sidebar.club': 'Клуб',
    'sidebar.players': 'Игроки',
    'sidebar.training': 'Тренировки',
    'sidebar.matches': 'Матчи',
    'sidebar.league': 'Лига',
    'sidebar.stadium': 'Стадион',
    'sidebar.finances': 'Финансы',
    'sidebar.transfers': 'Трансферы',
    'sidebar.challenges': 'Задания',
    'sidebar.manager': 'Менеджер',
    'auth.signInTitle': 'Войти в',
    'auth.signInDesc': 'Введите ваш email для доступа к команде',
    'auth.email': 'Эл. почта',
    'auth.password': 'Пароль',
    'auth.forgotPassword': 'Забыли пароль?',
    'auth.signIn': 'Войти',
    'auth.signingIn': 'Вход...',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.createAccount': 'Создать аккаунт',
    'auth.createAccountDesc': 'Зарегистрируйтесь и начните карьеру менеджера',
    'auth.haveAccount': 'Уже есть аккаунт?',
    'auth.terms': 'Продолжая, вы соглашаетесь с нашими Условиями и Политикой конфиденциальности.',
    'player.skill.finishing': 'Удар', 'player.skill.pace': 'Скорость',
    'player.skill.passing': 'Пас', 'player.skill.defense': 'Защита',
    'player.skill.dribbling': 'Дриблинг', 'player.skill.heading': 'Игра головой',
    'player.skill.stamina': 'Выносливость', 'player.skill.goalkeeper': 'Вратарь',
    'player.category.technical': 'Технические', 'player.category.physical': 'Физические',
    'player.form.excellent': 'Отлично', 'player.form.good': 'Хорошо',
    'player.form.average': 'Средне', 'player.form.poor': 'Плохо',
    'player.fitness': 'Физ. форма', 'player.goals': 'Голы', 'player.assists': 'Передачи',
    'player.value': 'Стоимость', 'player.wage': 'Зарплата', 'player.age': 'Возраст',
  },
  nl: {
    'landing.title': 'Manager Game | Sluit je aan bij de vrije voetbalwereld',
    'landing.getTeam': 'Kies je team',
    'landing.getTeamDesc': 'Begin met je eigen team — we zijn altijd op zoek naar nieuw talent!',
    'landing.signIn': 'Inloggen',
    'landing.signUp': 'Aanmelden',
    'landing.buildTrain': 'Bouw en train je team',
    'landing.buildTrainDesc': 'Ontwikkel je team door training. Beheer je financiën. Selecteer je beste spelers.',
    'landing.compete': 'Speel in competities',
    'landing.competeDesc': 'Doe mee aan competities en toernooien. Stijg door de divisies.',
    'landing.matchExp': 'Wedstrijdervaring',
    'landing.matchExpDesc': 'Bekijk live wedstrijden met onze realtime wedstrijdsimulator.',
    'landing.community': 'Community',
    'landing.communityDesc': 'Word lid van een levendige community van managers wereldwijd.',
    'landing.discordTitle': 'Sluit je aan bij de ontwikkelaarsgemeenschap!',
    'landing.chooseLanguage': 'Kies taal',
    'nav.myClub': 'Mijn Club',
    'nav.world': 'Wereld',
    'nav.groups': 'Groepen',
    'nav.forums': 'Forums',
    'nav.community': 'Community',
    'nav.help': 'Help',
    'nav.premium': 'Premium',
    'nav.mailbox': 'Postbus',
    'sidebar.overview': 'Overzicht',
    'sidebar.club': 'Club',
    'sidebar.players': 'Spelers',
    'sidebar.training': 'Training',
    'sidebar.matches': 'Wedstrijden',
    'sidebar.league': 'Competitie',
    'sidebar.stadium': 'Stadion',
    'sidebar.finances': 'Financiën',
    'sidebar.transfers': 'Transfers',
    'sidebar.challenges': 'Uitdagingen',
    'sidebar.manager': 'Manager',
    'auth.signInTitle': 'Inloggen bij',
    'auth.signInDesc': 'Voer je e-mail in om toegang te krijgen tot je team',
    'auth.email': 'E-mail',
    'auth.password': 'Wachtwoord',
    'auth.forgotPassword': 'Wachtwoord vergeten?',
    'auth.signIn': 'Inloggen',
    'auth.signingIn': 'Inloggen...',
    'auth.noAccount': 'Geen account?',
    'auth.createAccount': 'Maak een Account',
    'auth.createAccountDesc': 'Meld je aan om je voetbalmanagercarrière te starten',
    'auth.haveAccount': 'Al een account?',
    'auth.terms': 'Door verder te gaan, ga je akkoord met onze Servicevoorwaarden en Privacybeleid.',
    'player.skill.finishing': 'Afwerking', 'player.skill.pace': 'Snelheid',
    'player.skill.passing': 'Passing', 'player.skill.defense': 'Verdediging',
    'player.skill.dribbling': 'Dribbelen', 'player.skill.heading': 'Koppen',
    'player.skill.stamina': 'Uithoudingsvermogen', 'player.skill.goalkeeper': 'Keepersvaardigheid',
    'player.category.technical': 'Technisch', 'player.category.physical': 'Fysiek',
    'player.form.excellent': 'Uitstekend', 'player.form.good': 'Goed',
    'player.form.average': 'Gemiddeld', 'player.form.poor': 'Slecht',
    'player.fitness': 'Fitheid', 'player.goals': 'Doelpunten', 'player.assists': 'Assists',
    'player.value': 'Waarde', 'player.wage': 'Salaris', 'player.age': 'Leeftijd',
  },
  tr: {
    'landing.title': 'Yönetici Oyunu | Ücretsiz futbol dünyasına katıl',
    'landing.getTeam': 'Takımını al',
    'landing.getTeamDesc': 'Kendi takımınla başla — her zaman yeni yetenekler arıyoruz!',
    'landing.signIn': 'Giriş Yap',
    'landing.signUp': 'Kayıt Ol',
    'landing.buildTrain': 'Takımını kur ve antrenman yap',
    'landing.buildTrainDesc': 'Takımını antrenmanla geliştir. Finanslarını yönet. En iyi oyuncuları seç.',
    'landing.compete': 'Liglerde rekabet et',
    'landing.competeDesc': 'Liglere ve turnuvalara katıl. Divisionlar arasında yüksel.',
    'landing.matchExp': 'Maç Deneyimi',
    'landing.matchExpDesc': 'Gerçek zamanlı maç simülatörümüzle canlı maçları izle.',
    'landing.community': 'Topluluk',
    'landing.communityDesc': 'Dünya genelindeki yöneticilerden oluşan topluluğa katıl.',
    'landing.discordTitle': 'Geliştirici topluluğuna katılın!',
    'landing.chooseLanguage': 'Dil seçin',
    'nav.myClub': 'Kulübüm',
    'nav.world': 'Dünya',
    'nav.groups': 'Gruplar',
    'nav.forums': 'Forumlar',
    'nav.community': 'Topluluk',
    'nav.help': 'Yardım',
    'nav.premium': 'Premium',
    'nav.mailbox': 'Posta Kutusu',
    'sidebar.overview': 'Genel Bakış',
    'sidebar.club': 'Kulüp',
    'sidebar.players': 'Oyuncular',
    'sidebar.training': 'Antrenman',
    'sidebar.matches': 'Maçlar',
    'sidebar.league': 'Lig',
    'sidebar.stadium': 'Stadyum',
    'sidebar.finances': 'Finanslar',
    'sidebar.transfers': 'Transferler',
    'sidebar.challenges': 'Görevler',
    'sidebar.manager': 'Yönetici',
    'auth.signInTitle': 'Giriş yap:',
    'auth.signInDesc': 'Takımına erişmek için e-posta adresini gir',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.forgotPassword': 'Şifremi unuttum?',
    'auth.signIn': 'Giriş Yap',
    'auth.signingIn': 'Giriş yapılıyor...',
    'auth.noAccount': 'Hesabın yok mu?',
    'auth.createAccount': 'Hesap Oluştur',
    'auth.createAccountDesc': 'Futbol yönetici kariyerine başlamak için kaydol',
    'auth.haveAccount': 'Zaten hesabın var mı?',
    'auth.terms': 'Devam ederek, Hizmet Şartlarımızı ve Gizlilik Politikamızı kabul etmiş olursunuz.',
    'player.skill.finishing': 'Bitiricilik', 'player.skill.pace': 'Hız',
    'player.skill.passing': 'Pas', 'player.skill.defense': 'Defans',
    'player.skill.dribbling': 'Top Sürme', 'player.skill.heading': 'Kafa Vuruşu',
    'player.skill.stamina': 'Kondisyon', 'player.skill.goalkeeper': 'Kaleci',
    'player.category.technical': 'Teknik', 'player.category.physical': 'Fiziksel',
    'player.form.excellent': 'Mükemmel', 'player.form.good': 'İyi',
    'player.form.average': 'Ortalama', 'player.form.poor': 'Kötü',
    'player.fitness': 'Fiziksel Durum', 'player.goals': 'Gol', 'player.assists': 'Asist',
    'player.value': 'Değer', 'player.wage': 'Ücret', 'player.age': 'Yaş',
  },
  ja: {
    'landing.title': 'マネージャーゲーム | 無料サッカーワールドに参加しよう',
    'landing.getTeam': 'チームを取得',
    'landing.getTeamDesc': '自分のチームで始めよう — 新しい才能を常に探しています！',
    'landing.signIn': 'ログイン',
    'landing.signUp': '新規登録',
    'landing.buildTrain': 'チームを構築・トレーニング',
    'landing.buildTrainDesc': 'トレーニングでチームを発展させよう。財務を管理。最高の選手を選ぼう。',
    'landing.compete': 'リーグで競争',
    'landing.competeDesc': 'リーグやトーナメントに参加。ディビジョンを昇格しよう。',
    'landing.matchExp': 'マッチ体験',
    'landing.matchExpDesc': 'リアルタイムマッチシミュレーターでライブマッチを観戦。',
    'landing.community': 'コミュニティ',
    'landing.communityDesc': '世界中のマネージャーからなる活気あるコミュニティに参加しよう。',
    'landing.discordTitle': 'アイデアを共有する開発コミュニティに参加しよう！',
    'landing.chooseLanguage': '言語を選択',
    'nav.myClub': 'マイクラブ',
    'nav.world': 'ワールド',
    'nav.groups': 'グループ',
    'nav.forums': 'フォーラム',
    'nav.community': 'コミュニティ',
    'nav.help': 'ヘルプ',
    'nav.premium': 'プレミアム',
    'nav.mailbox': 'メールボックス',
    'sidebar.overview': '概要',
    'sidebar.club': 'クラブ',
    'sidebar.players': '選手',
    'sidebar.training': 'トレーニング',
    'sidebar.matches': '試合',
    'sidebar.league': 'リーグ',
    'sidebar.stadium': 'スタジアム',
    'sidebar.finances': '財務',
    'sidebar.transfers': '移籍',
    'sidebar.challenges': 'チャレンジ',
    'sidebar.manager': 'マネージャー',
    'auth.signInTitle': 'ログイン：',
    'auth.signInDesc': 'チームへのアクセスにメールを入力してください',
    'auth.email': 'メール',
    'auth.password': 'パスワード',
    'auth.forgotPassword': 'パスワードをお忘れですか？',
    'auth.signIn': 'ログイン',
    'auth.signingIn': 'ログイン中...',
    'auth.noAccount': 'アカウントがない方は',
    'auth.createAccount': 'アカウントを作成',
    'auth.createAccountDesc': '登録してサッカーマネージャーのキャリアを始めよう',
    'auth.haveAccount': 'すでにアカウントをお持ちの方は',
    'auth.terms': '続行することで、利用規約とプライバシーポリシーに同意したことになります。',
    'player.skill.finishing': 'シュート力', 'player.skill.pace': 'スピード',
    'player.skill.passing': 'パス', 'player.skill.defense': 'ディフェンス',
    'player.skill.dribbling': 'ドリブル', 'player.skill.heading': 'ヘディング',
    'player.skill.stamina': 'スタミナ', 'player.skill.goalkeeper': 'GK能力',
    'player.category.technical': 'テクニカル', 'player.category.physical': 'フィジカル',
    'player.form.excellent': '絶好調', 'player.form.good': '好調',
    'player.form.average': '普通', 'player.form.poor': '不調',
    'player.fitness': 'フィットネス', 'player.goals': 'ゴール', 'player.assists': 'アシスト',
    'player.value': '市場価値', 'player.wage': '週給', 'player.age': '年齢',
  },
  ko: {
    'landing.title': '감독 게임 | 무료 축구 세계에 참여하세요',
    'landing.getTeam': '팀 받기',
    'landing.getTeamDesc': '자신의 팀으로 시작하세요 — 항상 새로운 인재를 찾고 있습니다!',
    'landing.signIn': '로그인',
    'landing.signUp': '회원가입',
    'landing.buildTrain': '팀을 구성하고 훈련하세요',
    'landing.buildTrainDesc': '훈련을 통해 팀을 발전시키세요. 재정을 관리하세요. 최고의 선수를 선발하세요.',
    'landing.compete': '리그에서 경쟁하세요',
    'landing.competeDesc': '리그와 토너먼트에 참가하세요. 디비전을 올라가세요.',
    'landing.matchExp': '경기 경험',
    'landing.matchExpDesc': '실시간 경기 시뮬레이터로 라이브 경기를 시청하세요.',
    'landing.community': '커뮤니티',
    'landing.communityDesc': '전 세계 감독들의 활발한 커뮤니티에 참여하세요.',
    'landing.discordTitle': '개발 커뮤니티에 참여하여 아이디어를 공유하세요!',
    'landing.chooseLanguage': '언어 선택',
    'nav.myClub': '내 클럽',
    'nav.world': '세계',
    'nav.groups': '그룹',
    'nav.forums': '포럼',
    'nav.community': '커뮤니티',
    'nav.help': '도움말',
    'nav.premium': '프리미엄',
    'nav.mailbox': '우편함',
    'sidebar.overview': '개요',
    'sidebar.club': '클럽',
    'sidebar.players': '선수',
    'sidebar.training': '훈련',
    'sidebar.matches': '경기',
    'sidebar.league': '리그',
    'sidebar.stadium': '경기장',
    'sidebar.finances': '재정',
    'sidebar.transfers': '이적',
    'sidebar.challenges': '도전',
    'sidebar.manager': '감독',
    'auth.signInTitle': '로그인:',
    'auth.signInDesc': '팀에 접근하려면 이메일을 입력하세요',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'auth.forgotPassword': '비밀번호를 잊으셨나요?',
    'auth.signIn': '로그인',
    'auth.signingIn': '로그인 중...',
    'auth.noAccount': '계정이 없으신가요?',
    'auth.createAccount': '계정 만들기',
    'auth.createAccountDesc': '축구 감독 커리어를 시작하려면 가입하세요',
    'auth.haveAccount': '계정이 있으신가요?',
    'auth.terms': '계속하면 서비스 약관 및 개인정보 처리방침에 동의하는 것입니다.',
    'player.skill.finishing': '결정력', 'player.skill.pace': '속도',
    'player.skill.passing': '패스', 'player.skill.defense': '수비',
    'player.skill.dribbling': '드리블', 'player.skill.heading': '헤딩',
    'player.skill.stamina': '체력', 'player.skill.goalkeeper': '골키퍼',
    'player.category.technical': '기술', 'player.category.physical': '신체',
    'player.form.excellent': '최상', 'player.form.good': '좋음',
    'player.form.average': '보통', 'player.form.poor': '나쁨',
    'player.fitness': '피트니스', 'player.goals': '골', 'player.assists': '어시스트',
    'player.value': '가치', 'player.wage': '주급', 'player.age': '나이',
  },
};

const languageNames = {
  en: 'English',
  es: 'Español',
  it: 'Italiano',
  de: 'Deutsch',
  pl: 'Polski',
  pt: 'Português',
  fr: 'Français',
  zh: '中文',
  ru: 'Русский',
  nl: 'Nederlands',
  tr: 'Türkçe',
  ja: '日本語',
  ko: '한국어',
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('app-language') as Language;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { languageNames };
