// Country name to ISO country code mapping
// This maps country/region names to their corresponding ISO 3166-1 alpha-2 country codes
// Used for displaying flags via the flagcdn.com service

export const specialCases: Record<string, string> = {
  // Common variations and special cases
  'England': 'gb-eng',
  'Scotland': 'gb-sct', 
  'Wales': 'gb-wls',
  'Northern Ireland': 'gb-nir',
  'United States': 'us',
  'USA': 'us',
  'United Kingdom': 'gb',
  'UK': 'gb',
  'South Korea': 'kr',
  'North Korea': 'kp',
  'Czech Republic': 'cz',
  'Czechia': 'cz', // Added mapping for Czechia
  'Russia': 'ru',
  'China': 'cn',
  'People\'s Republic of China': 'cn', // Added mapping for People's Republic of China
  'Taiwan': 'tw',
  'Hong Kong': 'hk',
  'Macau': 'mo',
  'Vatican City': 'va',
  'Bosnia and Herzegovina': 'ba',
  'Trinidad and Tobago': 'tt',
  'São Tomé and Príncipe': 'st',
  'Saint Kitts and Nevis': 'kn',
  'Saint Lucia': 'lc',
  'Saint Vincent and the Grenadines': 'vc',
  'Antigua and Barbuda': 'ag',
  'Solomon Islands': 'sb',
  'Marshall Islands': 'mh',
  'Papua New Guinea': 'pg',
  'East Timor': 'tl',
  'Timor-Leste': 'tl',
  'Cape Verde': 'cv',
  'Ivory Coast': 'ci',
  'Democratic Republic of the Congo': 'cd',
  'Republic of the Congo': 'cg',
  'Central African Republic': 'cf',
  'Equatorial Guinea': 'gq',
  'Guinea-Bissau': 'gw',
  'Burkina Faso': 'bf',
  'Sierra Leone': 'sl',
  'Côte d\'Ivoire': 'ci',
  'Australia': 'au',
  'Costa Rica': 'cr', // Added mapping for Costa Rica
  'Dominican Republic': 'do', // Added mapping for Dominican Republic
  'El Salvador': 'sv', // Added mapping for El Salvador
  'North Macedonia': 'mk', // Added mapping for North Macedonia
  'Puerto Rico': 'pr', // Added mapping for Puerto Rico
  'United Arab Emirates': 'ae', // Added mapping for United Arab Emirates
};

/**
 * Get the ISO country code for a given country name
 * @param countryName The country name to look up
 * @returns The ISO 3166-1 alpha-2 country code
 */
export function getCountryCode(countryName: string): string {
  if (!countryName) return '';
  
  // Check special cases first
  const specialCase = specialCases[countryName];
  if (specialCase) {
    return specialCase;
  }
  
  // For most countries, we can derive the code by:
  // 1. Converting to lowercase
  // 2. Replacing spaces with nothing or handling common patterns
  const normalized = countryName.toLowerCase()
    .replace(/\s+/g, '')
    .replace(/[^a-z]/g, '');
  
  // Common country mappings that follow patterns
  const commonMappings: Record<string, string> = {
    'afghanistan': 'af',
    'albania': 'al',
    'algeria': 'dz',
    'andorra': 'ad',
    'angola': 'ao',
    'argentina': 'ar',
    'armenia': 'am',
    'australia': 'au',
    'austria': 'at',
    'azerbaijan': 'az',
    'bahamas': 'bs',
    'bahrain': 'bh',
    'bangladesh': 'bd',
    'barbados': 'bb',
    'belarus': 'by',
    'belgium': 'be',
    'belize': 'bz',
    'benin': 'bj',
    'bhutan': 'bt',
    'bolivia': 'bo',
    'brazil': 'br',
    'brunei': 'bn',
    'bulgaria': 'bg',
    'cambodia': 'kh',
    'cameroon': 'cm',
    'canada': 'ca',
    'chad': 'td',
    'chile': 'cl',
    'colombia': 'co',
    'comoros': 'km',
    'croatia': 'hr',
    'cuba': 'cu',
    'cyprus': 'cy',
    'denmark': 'dk',
    'djibouti': 'dj',
    'dominica': 'dm',
    'ecuador': 'ec',
    'egypt': 'eg',
    'estonia': 'ee',
    'ethiopia': 'et',
    'fiji': 'fj',
    'finland': 'fi',
    'france': 'fr',
    'gabon': 'ga',
    'gambia': 'gm',
    'georgia': 'ge',
    'germany': 'de',
    'ghana': 'gh',
    'greece': 'gr',
    'grenada': 'gd',
    'guatemala': 'gt',
    'guinea': 'gn',
    'guyana': 'gy',
    'haiti': 'ht',
    'honduras': 'hn',
    'hungary': 'hu',
    'iceland': 'is',
    'india': 'in',
    'indonesia': 'id',
    'iran': 'ir',
    'iraq': 'iq',
    'ireland': 'ie',
    'israel': 'il',
    'italy': 'it',
    'jamaica': 'jm',
    'japan': 'jp',
    'jordan': 'jo',
    'kazakhstan': 'kz',
    'kenya': 'ke',
    'kiribati': 'ki',
    'kuwait': 'kw',
    'kyrgyzstan': 'kg',
    'laos': 'la',
    'latvia': 'lv',
    'lebanon': 'lb',
    'lesotho': 'ls',
    'liberia': 'lr',
    'libya': 'ly',
    'liechtenstein': 'li',
    'lithuania': 'lt',
    'luxembourg': 'lu',
    'madagascar': 'mg',
    'malawi': 'mw',
    'malaysia': 'my',
    'maldives': 'mv',
    'mali': 'ml',
    'malta': 'mt',
    'mauritania': 'mr',
    'mauritius': 'mu',
    'mexico': 'mx',
    'micronesia': 'fm',
    'moldova': 'md',
    'monaco': 'mc',
    'mongolia': 'mn',
    'montenegro': 'me',
    'morocco': 'ma',
    'mozambique': 'mz',
    'myanmar': 'mm',
    'namibia': 'na',
    'nauru': 'nr',
    'nepal': 'np',
    'netherlands': 'nl',
    'newzealand': 'nz',
    'nicaragua': 'ni',
    'niger': 'ne',
    'nigeria': 'ng',
    'norway': 'no',
    'oman': 'om',
    'pakistan': 'pk',
    'palau': 'pw',
    'panama': 'pa',
    'paraguay': 'py',
    'peru': 'pe',
    'philippines': 'ph',
    'poland': 'pl',
    'portugal': 'pt',
    'qatar': 'qa',
    'romania': 'ro',
    'rwanda': 'rw',
    'samoa': 'ws',
    'sanmarino': 'sm',
    'saudiarabia': 'sa',
    'senegal': 'sn',
    'serbia': 'rs',
    'seychelles': 'sc',
    'singapore': 'sg',
    'slovakia': 'sk',
    'slovenia': 'si',
    'somalia': 'so',
    'southafrica': 'za',
    'spain': 'es',
    'srilanka': 'lk',
    'sudan': 'sd',
    'suriname': 'sr',
    'sweden': 'se',
    'switzerland': 'ch',
    'syria': 'sy',
    'tajikistan': 'tj',
    'tanzania': 'tz',
    'thailand': 'th',
    'togo': 'tg',
    'tonga': 'to',
    'tunisia': 'tn',
    'turkey': 'tr',
    'turkmenistan': 'tm',
    'tuvalu': 'tv',
    'uganda': 'ug',
    'ukraine': 'ua',
    'uruguay': 'uy',
    'uzbekistan': 'uz',
    'vanuatu': 'vu',
    'venezuela': 've',
    'vietnam': 'vn',
    'yemen': 'ye',
    'zambia': 'zm',
    'zimbabwe': 'zw',
  };
  
  return commonMappings[normalized] || '';
}
