
// Maps EXACT country names from leagues_regions.name → ISO 4217 currency code
// Covers all 129 countries in the game
export const COUNTRY_CURRENCY: Record<string, string> = {
  // ── Europe – Euro zone ──────────────────────────────────────────────────
  Spain: "EUR",
  France: "EUR",
  Germany: "EUR",
  Italy: "EUR",
  Portugal: "EUR",
  Netherlands: "EUR",
  Belgium: "EUR",
  Greece: "EUR",
  Austria: "EUR",
  Finland: "EUR",
  Ireland: "EUR",
  Luxembourg: "EUR",
  Slovakia: "EUR",
  Slovenia: "EUR",
  Croatia: "EUR",
  Cyprus: "EUR",
  Malta: "EUR",
  Estonia: "EUR",
  Latvia: "EUR",
  Lithuania: "EUR",
  Montenegro: "EUR",
  Kosovo: "EUR",

  // ── Europe – non-Euro ───────────────────────────────────────────────────
  England: "GBP",
  Scotland: "GBP",
  Wales: "GBP",
  "Northern Ireland": "GBP",
  Switzerland: "CHF",
  Sweden: "SEK",
  Norway: "NOK",
  Denmark: "DKK",
  Poland: "PLN",
  "Czech Republic": "CZK",
  Hungary: "HUF",
  Romania: "RON",
  Bulgaria: "BGN",
  Serbia: "RSD",
  Turkey: "TRY",
  Russia: "RUB",
  Ukraine: "UAH",
  Belarus: "BYN",
  Iceland: "ISK",
  Albania: "ALL",
  "North Macedonia": "MKD",
  "Bosnia and Herzegovina": "BAM",
  Georgia: "GEL",
  Armenia: "AMD",
  Azerbaijan: "AZN",
  Moldova: "MDL",

  // ── Americas ────────────────────────────────────────────────────────────
  "United States": "USD",
  Canada: "CAD",
  Mexico: "MXN",
  Brazil: "BRL",
  Argentina: "ARS",
  Colombia: "COP",
  Chile: "CLP",
  Peru: "PEN",
  Ecuador: "USD",
  Bolivia: "BOB",
  Paraguay: "PYG",
  Uruguay: "UYU",
  Venezuela: "VES",
  "Costa Rica": "CRC",
  Honduras: "HNL",
  Guatemala: "GTQ",
  "El Salvador": "USD",
  Panama: "USD",
  Nicaragua: "NIO",
  Jamaica: "JMD",
  Cuba: "CUP",
  Haiti: "HTG",
  "Dominican Republic": "DOP",
  "Trinidad and Tobago": "TTD",

  // ── Africa – CFA Franc BCEAO (XOF) – West Africa ───────────────────────
  Senegal: "XOF",
  "Ivory Coast": "XOF",
  Mali: "XOF",
  "Burkina Faso": "XOF",
  Benin: "XOF",
  Togo: "XOF",
  Niger: "XOF",
  Guinea: "GNF",
  Mauritania: "MRU",
  "Sierra Leone": "SLL",
  Liberia: "LRD",

  // ── Africa – CFA Franc BEAC (XAF) – Central Africa ─────────────────────
  Cameroon: "XAF",
  Gabon: "XAF",
  Congo: "XAF",
  "DR Congo": "CDF",

  // ── Africa – other ──────────────────────────────────────────────────────
  Nigeria: "NGN",
  "South Africa": "ZAR",
  Egypt: "EGP",
  Morocco: "MAD",
  Algeria: "DZD",
  Tunisia: "TND",
  Ghana: "GHS",
  Kenya: "KES",
  Tanzania: "TZS",
  Ethiopia: "ETB",
  Uganda: "UGX",
  Zambia: "ZMW",
  Zimbabwe: "USD",
  Angola: "AOA",
  Mozambique: "MZN",
  Rwanda: "RWF",
  Sudan: "SDG",
  Libya: "LYD",
  Namibia: "NAD",
  Botswana: "BWP",
  Somalia: "SOS",

  // ── Middle East ─────────────────────────────────────────────────────────
  "Saudi Arabia": "SAR",
  "United Arab Emirates": "AED",
  Qatar: "QAR",
  Kuwait: "KWD",
  Bahrain: "BHD",
  Oman: "OMR",
  Jordan: "JOD",
  Iraq: "IQD",
  Iran: "IRR",

  // ── Asia & Oceania ──────────────────────────────────────────────────────
  Japan: "JPY",
  "South Korea": "KRW",
  China: "CNY",
  India: "INR",
  Australia: "AUD",
  "New Zealand": "NZD",
  Indonesia: "IDR",
  Thailand: "THB",
  Vietnam: "VND",
  Malaysia: "MYR",
  Singapore: "SGD",
  Philippines: "PHP",
  Pakistan: "PKR",
  Bangladesh: "BDT",
  "Sri Lanka": "LKR",
  Kazakhstan: "KZT",
  Uzbekistan: "UZS",
  Tajikistan: "TJS",
};

/** Returns the ISO 4217 currency code for a given country name, defaults to EUR */
export function getCurrencyCode(countryName: string | null | undefined): string {
  if (!countryName) return "EUR";
  return COUNTRY_CURRENCY[countryName] ?? "EUR";
}
